version: "3.9"
services:
  web:
    build: .
    container_name: article-web
    ports:
      - "8000:8000"
    environment:
      DOCKER_ENV: "true"
      TZ: Asia/Shanghai
      DATABASE_URL: postgresql://postgres:example@db:5432/postgres
    depends_on:
      - db
    # volumes:
    #   - ./app:/app/app           # 如需开发时代码热更，可解除注释
    #   - ./frontend/dist:/frontend/dist
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: article-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example        # 强烈建议生产环境改强密码
      POSTGRES_DB: postgres
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: